
Imports dynamicpdf_vbnet_examples.dynamicpdf_vb_examples.Examples
Imports dynamicpdf_vbnet_examples.dynamicpdf_vbnet_examples.Examples
Imports dynamicpdf_vbnet_examples.DynamicPDFCoreSuite.Examples

Module Program
    Sub Main(args As String())

        Console.WriteLine(AppContext.BaseDirectory)
        Util.CreateOutput()
        AddExistingContent.Run()
        AddNewContentExample.Run()
        AreaChartExample.Run()
        BarcodeExample.Run()
        BarChartsExample.Run()
        BookmarkOutlineExample.Run()
        CertificateExample.Run()
        ChartLegendsExample.Run()
        ChartsXaxisExample.Run()
        ChartYaxisExamples.Run()
        ChartTwoDiffPlotAreasExample.Run()
        ColorsExample.Run()
        ColumnChartExample.Run()
        CreatePDF.Run()
        DigitalSignatureExample.Run()
        DocumentSectioningExample.Run()
        EncryptPDF.Run()
        EvenOddTemplateExample.Run()
        EventsExample.Run()
        ExtractingExistingContent.Run()
        FontsExample.Run()
        FontKerning.Run()
        FormattedTextAreaExample.Run()
        FormFieldsRemoveAddExample.Run()
        FormFillingExample.Run()
        GridLinesExample.Run()
        GroupingExample.Run()
        HeaderFooterTemplateExample.Run()
        HtmlAreaExample.Run()
        HtmlLayoutExample.Run()
        Image3dExample.Run()
        InteractiveFormsExample.Run()
        JavaScriptExample.Run()
        LineChartsExample.Run()
        ListsExample.Run()
        ListContinuationExample.Run()
        MergePdfExample.Run()
        MergerActions.Run()
        PagesExample.Run()
        PdfUaExample.Run()
        PdfXCompatibleExample.Run()
        PdfACompatibleExample.Run()
        PieChartsExample.Run()
        ReadFormFieldsExample.Run()
        RetrievingFormFieldsExample.Run()
        StampTemplateExample.Run()
        TextContinuationExample.Run()
        TableExample.Run()
        TableContinuationExample.Run()
        TemplateExample.Run()
        XmpMetadataExample.Run()
    End Sub
End Module
