
Imports dynamicpdf_vbnet_examples.dynamicpdf_vb_examples.Examples
Imports dynamicpdf_vbnet_examples.dynamicpdf_vbnet_examples.Examples
Imports dynamicpdf_vbnet_examples.DynamicPDFCoreSuite.Examples

Module Program
    Sub Main(args As String())

        Console.WriteLine(AppContext.BaseDirectory)
        Util.CreateOutput()
        AcroFormFilling.Run()
        AcroFormFillingMerge.Run()
        AddExistingContent.Run()
        AddFormFieldsExample.Run()
        AddImageExample.Run()
        AddNewContentExample.Run()
        AddSignatureExample.Run()
        AnnotationShowHideActionExample.Run()
        AreaChartExample.Run()
        AutolayoutExample.Run()
        BarcodeExample.Run()
        BarChartsExample.Run()
        BookmarkOutlineExample.Run()
        CertificateExample.Run()
        ChartsExample.Run()
        ChartLegendsExample.Run()
        ChartsXaxisExample.Run()
        ChartYaxisExamples.Run()
        ChartTwoDiffPlotAreasExample.Run()
        ColorsExample.Run()
        ColumnChartExample.Run()
        CombinePDFs.Run()
        CreatePDF.Run()
        CustomPageElementExample.Run()
        DigitalSignatureExample.Run()
        DocumentSectioningExample.Run()
        EncryptPDF.Run()
        EvenOddTemplateExample.Run()
        EventsExample.Run()
        ExistingOutlinesExample.Run()
        ExtractingExistingContent.Run()
        FontsExample.Run()
        FontKerning.Run()
        FormattedTextAreaExample.Run()
        FormFieldsReadOnly.Run()
        FormFieldsRemoveAddExample.Run()
        FormFillingExample.Run()
        GenerateReportExample.Run()
        GridLinesExample.Run()
        GroupingExample.Run()
        HeaderFooterTemplateExample.Run()
        HtmlAreaExample.Run()
        HtmlLayoutExample.Run()
        Image3dExample.Run()
        ImageStampExample.Run()
        InteractiveFormsExample.Run()
        JavaScriptExample.Run()
        LayoutEventsExample.Run()
        LineChartsExample.Run()
        ListsExample.Run()
        ListContinuationExample.Run()
        MergePdfExample.Run()
        FormFdfExample.Run()
        PagesExample.Run()
        PageNumbers.Run()
        PdfUaExample.Run()
        PdfXCompatibleExample.Run()
        PdfACompatibleExample.Run()
        PieChartsExample.Run()
        ReadFormFieldsExample.Run()
        RetrievingFormFieldsExample.Run()
        SplitPdfExample.Run()
        StampTemplateExample.Run()
        TextContinuationExample.Run()
        TableExample.Run()
        TableContinuationExample.Run()
        TaggedPdfExample.Run()
        TemplateExample.Run()
        TextEncodingExample.Run()
        TextFormattingExample.Run()
        TiffToPDF.Run()
        WatermarkExample.Run()
        XmpMetadataExample.Run()
    End Sub
End Module
