using dynamicpdf_csharp_examples.Examples;
using DynamicPDFCoreSuite.Examples;

namespace DynamicPDFCoreSuite
{
    class Program
    {
        static void Main(string[] args)
        {

            Util.CreatePath("Output");
            
            AddExistingContent.Run();
             AddNewContentExample.Run();
             AcroFormFilling.Run();
            AcroFormFillingMerge.Run();
             Actions.Run();
             AddImageExample.Run();
             AddFormFieldsExample.Run();
             AddNewContentExample.Run();
             AddShapeExample.Run();
             AddSignatureExample.Run();
             AddTemplateExample.Run();
             AnnotationShowHideActionExample.Run();
             AreaChartExample.Run();
             AutolayoutExample.Run();
             BarChartsExample.Run();
             BarcodeExample.Run();
             BookmarkOutlineExample.Run();
             CertificateExample.Run();
             ChartsExample.Run();
             ChartLegendsExample.Run();
             ChartsXaxisExample.Run();
             ChartYaxisExamples.Run();
             ChartTwoDiffPlotAreasExample.Run();
             ColorsExample.Run();
             ColumnChartExample.Run();
             CombinePDFs.Run();
             CreatePDF.Run();
             CustomPageElementExample.Run();
             DigitalSignatureExample.Run();
             DiskBufferingExample.Run();
             DocumentSectioningExample.Run();
             EmbeddingFilesExample.Run();
             EncryptPDF.Run();
             EventsExample.Run();
             EvenOddTemplateExample.Run();
             ExistingOutlinesExample.Run();
             ExtractingExistingContent.Run();
             FontsExample.Run();
             FontKerning.Run();
             FormattedTextAreaExample.Run();
             FormFieldsRemoveAddExample.Run();
             FormFieldsReadOnly.Run();
             FormFillingExample.Run();
             FormFlatteningExample.Run();
             GenerateReportExample.Run();
             GridLinesExample.Run();
             GroupingExample.Run();
             HeaderFooterTemplateExample.Run();
             HtmlAreaExample.Run();
             HtmlLayoutExample.Run();
             HtmlToPdf.Run();
             HtmlAreaExample.Run();
             Image3dExample.Run();
             ImageStampExample.Run();
             InteractiveFormsExample.Run();
             JavaScriptExample.Run();
             LayoutEngineExample.Run();
             LayoutGridExample.Run();
             LayoutEventsExample.Run();
             LineChartsExample.Run();
             ListContinuationExample.Run();
             ListsExample.Run();
             FormFdfExample.Run();
             MergePdfExample.Run();
             PackagePdfExample.Run();
             PagesExample.Run();
             PageLinkExample.Run();
             PageNumbers.Run();
             PasswordProtectPDF.Run();
             PdfACompatibleExample.Run();
             PdfUaExample.Run();
             PdfXCompatibleExample.Run();
             PdfACompatibleExample.Run();
             PackagePdfExample.Run();
             PieChartsExample.Run();
             ReaderEventExample.Run();
             ReadFormFieldsExample.Run();
            RemovingFormFieldsExample.Run();
             RetrievingFormFieldsExample.Run();
             SectionsExample.Run();
            ShapesExample.Run();
             SplitPdfExample.Run();
             StampTemplateExample.Run();
             TableExample.Run();
             TableContinuationExample.Run();
             TaggedPdfExample.Run();
             TemplateExample.Run();
             TextContinuationExample.Run();
             TextEncodingExample.Run();
             TextFormattingExample.Run();
             TiffToPDF.Run();
             WatermarkExample.Run();
             XmpMetadataExample.Run();
             XYScatterChartExample.Run(); 
        }
    }
}
