using DynamicPDFCoreSuite.Examples;

namespace DynamicPDFCoreSuite
{
    class Program
    {
        static void Main(string[] args)
        {

            Util.CreatePath("Output");

            AcroformExamineExample.Run();
            AcroFormFilling.Run();
            Actions.Run();
            AddImageExample.Run();
            AddFormFieldsExample.Run();
            AddNewContentExample.Run();
            AddShapeExample.Run();
            AddSignatureExample.Run();
            AddTemplateExample.Run();
            AnnotationsExample.Run();
            AreaChartExample.Run();
            BarChartsExample.Run();
            BarcodeExample.Run();
            BookmarkOutlineExample.Run();
            CertificateExample.Run();
            ChartsExample.Run();
            ChartLegendsExample.Run();
            ChartsXaxisExample.Run();
            ChartYaxisExamples.Run();
            ChartTwoDiffPlotAreasExample.Run();
            ColorsExample.Run();
            ColumnChartExample.Run();
            CombinePDFs.Run();
            CreatePDF.Run();
            DigitalSignatureExample.Run();
            DiskBufferingExample.Run();
            DocumentSectioningExample.Run();
            EmbeddingFilesExample.Run();
            EncryptPDF.Run();
            EventsExample.Run();
            EvenOddTemplateExample.Run();
            FontsExample.Run();
            FontKerning.Run();
            FormattedTextAreaExample.Run();
            FormFieldsAddExample.Run();
            FormFieldsReadOnly.Run();
            FormFlatteningExample.Run();
            GenerateReportExample.Run();
            GridLinesExample.Run();
            GroupingExample.Run();
            HeaderFooterTemplateExample.Run();
            HtmlAreaExample.Run();
            HtmlLayoutExample.Run();
            HtmlToPdf.Run();
            HtmlAreaExample.Run();
            Image3dExample.Run();
            ImageStampExample.Run();
            InteractiveFormsExample.Run();
            JavascriptActionExample.Run();
            LayoutEngineExample.Run();
            LayoutGridExample.Run();
            LineChartsExample.Run();
            ListContinuationExample.Run();
            ListsExample.Run();
            MergePDFs.Run();
            PackagePdfExample.Run();
            PagesExample.Run();
            PageLinkExample.Run();
            PageNumbers.Run();
            PasswordProtectPDF.Run();
            PdfACompatibleExample.Run();
            PdfUaExample.Run();
            PdfXCompatibleExample.Run();
            PdfACompatibleExample.Run();
            PackagePdfExample.Run();
            PieChartsExample.Run();
            ReaderEventExample.Run();
            ReadFormFieldsExample.Run();
            SectionsExample.Run();
            SplitPDF.Run();
            StampTemplateExample.Run();                     
            TableExample.Run();
            TableContinuationExample.Run();
            TaggedPdfExample.Run();
            TemplateExample.Run();
            TextContinuationExample.Run();
            TextEncodingExample.Run();
            TextFormattingExample.Run();
            TiffToPDF.Run();
            WatermarkExample.Run();
            XmpMetadataExample.Run();
            XYScatterChartExample.Run();
        }
    }
}
